server:
  port: 6868
spring:
  application:
    name: tensquare_eureka
eureka:
  client:
    register-with-eureka: false #是否将自己注册到eureka中
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka